export const MOODS = [
  "calm",
  "energized",
  "focused",
  "tired",
  "content",
  "restless",
  "grateful",
  "curious",
] as const

export const JOURNAL_TAGS = [
  "work",
  "family",
  "health",
  "learning",
  "outdoors",
  "music",
  "cooking",
  "reflection",
] as const

export const OPENERS = [
  "Slow start this morning, but the day found its rhythm.",
  "Up early and straight into the day before the house woke up.",
  "A gray, quiet day that turned out better than it looked.",
  "Busy from the first coffee to the last email.",
  "One of those days where everything took longer than planned.",
  "Good energy today, most of it spent where it mattered.",
  "A day of small wins and one stubborn problem.",
  "Mostly an ordinary day, which is its own kind of good.",
  "Woke up to rain on the window and didn't mind it for once.",
  "Every plan for today got rearranged by nine a.m., and it was fine.",
  "Not a productive day by any conventional metric, and I'm trying not to care.",
  "The kind of day that's hard to describe without sounding boring, which is its own compliment.",
] as const

export const SENTENCES = [
  "Work was a steady stream of meetings, but the afternoon block stayed clear for deep work.",
  "Spent an hour untangling a problem that turned out to have a one-line fix.",
  "The walk after lunch is quickly becoming the best part of the day.",
  "Made real progress on the side project, mostly by deleting things.",
  "Dinner was improvised from whatever was left in the fridge and somehow worked.",
  "The garden needs attention, but it will have to wait for the weekend.",
  "Read a few chapters before bed instead of scrolling, and it made a difference.",
  "Caught up on messages that had been piling up all week.",
  "The gym was quiet, so the whole session took half the usual time.",
  "Sketched out a plan for next month that already feels too ambitious.",
  "Music helped push through the boring part of the afternoon.",
  "Tried a new route home and it added ten minutes and one great view.",
  "The kids' schedule ran the evening, as usual, and that was fine.",
  "Wrote down three things that went well, a habit worth keeping.",
  "A long call with an old friend rearranged the whole evening for the better.",
  "The weather flipped twice before noon and settled on pleasant.",
  "Spent too long tweaking something nobody will ever notice, and enjoyed it.",
  "Cooked a double batch so tomorrow's lunch is already sorted.",
  "The inbox reached zero for about eleven minutes.",
  "Fixed the squeaky door that has been announcing everyone for months.",
  "Read for an hour with no podcast queued up for after, no task-list guilt.",
  "Chopped vegetables for longer than strictly necessary; it's basically meditation at this point.",
  "Took the long way on the walk on purpose, no destination in mind.",
  "The phone went in the drawer at nine, not just on silent, and the evening felt longer for it.",
  "Reorganized one shelf and somehow that made the whole room feel different.",
  "Burned the first attempt at dinner and made peace with ordering in.",
  "Noticed the same tree on the commute has started turning color.",
  "Spent the coffee break actually looking out the window instead of at a screen.",
] as const

export const HIGHLIGHTS = [
  "Finished the report a day ahead of schedule",
  "Long walk in the ravine at golden hour",
  "Finally organized the desk drawers",
  "Great coffee and an even better conversation",
  "New personal best on the evening run",
  "Found the perfect quote for the presentation",
  "Homemade bread actually rose this time",
  "Cleared the weekend for the family trip",
  "Read three chapters in one sitting for the first time in months",
  "The garden finally looks intentional instead of surviving",
  "Fixed something on the first try for once",
  "A whole afternoon with nowhere to be",
] as const

export const TASKS = [
  "Book the dentist appointment",
  "Reply to the insurance email",
  "Draft the project outline",
  "Water the plants",
  "Prep Sunday dinner",
  "Back up the photo library",
  "Return the library books",
  "Plan next week's workouts",
] as const

export const REFLECTIONS = [
  "Progress is quiet; it rarely announces itself.",
  "Most problems shrink when written down.",
  "Attention is the only currency that matters.",
  "Slow is smooth, and smooth is fast.",
  "The streak matters more than the score.",
  "There's a version of 'productive' that's really just anxiety about not doing enough.",
  "The things I remember most clearly are rarely the deliverables I shipped.",
  "Maybe the ratio of slow to fast just needs recalibrating.",
  "Busy and effective are not the same thing, and I keep mixing them up.",
] as const
