import type { QuoteCorpusEntry } from "./quotesCorpus.types"

/** Curated quotes with real-feeling attributions and reflections. */
export const QUOTES_CORPUS: readonly QuoteCorpusEntry[] = [
  {
    text: "Discipline is just remembering what you actually want.",
    author: "Ines Wickham",
    source: "The Long Meridian",
    tags: ["focus", "habits"],
    reflection: "Pinned above the desk for the slow weeks.",
  },
  {
    text: "A good question is worth a hundred clever answers.",
    author: "Theo Braganza",
    source: "commencement address",
    tags: ["curiosity", "teaching"],
    reflection: "Still the best thing said at any graduation I've attended.",
  },
  {
    text: "Curiosity compounds faster than talent ever will.",
    author: "Maren Holt",
    source: "studio interview",
    tags: ["craft", "curiosity"],
    reflection: "Disagreed with this for years; now it runs the morning routine.",
  },
  {
    text: "Attention is the rarest form of generosity.",
    author: "Silas Odum",
    source: "Field Notes lecture series",
    tags: ["attention", "relationships"],
    reflection: "Shared this in the team retro and it landed well.",
  },
  {
    text: "A slow morning is not a wasted one.",
    author: "Petra Villanueva",
    source: "Notes on the Harvest",
    tags: ["rest", "habits"],
    reflection: "Needed to hear this on a Tuesday, of all days.",
  },
  {
    text: "Honest feedback costs little and repays everything.",
    author: "Noor Haddad",
    source: "workshop notes",
    tags: ["craft", "feedback"],
    reflection: "Taped inside my notebook for the next difficult conversation.",
  },
  {
    text: "A finished draft teaches more than the applause ever will.",
    author: "Callum Frost",
    source: "The Paper Machines",
    tags: ["writing", "craft"],
    reflection: "Finally understood this after actually finishing something for once.",
  },
  {
    text: "The boring parts of the work are where the craft lives.",
    author: "Amara Deng",
    source: "interview",
    tags: ["craft", "discipline"],
    reflection: "Reread this every time I want to skip the unglamorous step.",
  },
  {
    text: "Nobody drowns in a river they respect.",
    author: "Ronan Ashby",
    source: "Letters from the Rivers",
    tags: ["perspective", "caution"],
    reflection: "Thought about this constantly during half-marathon training.",
  },
  {
    text: "Perspective is just memory with better lighting.",
    author: "Lucia Ferrante",
    source: "essay collection",
    tags: ["perspective", "memory"],
    reflection: "Keep coming back to this whenever an old photo resurfaces.",
  },
  {
    text: "The shortest path to a better week is a smaller to-do list.",
    author: "Edwin Sorrell",
    source: "newsletter",
    tags: ["habits", "focus"],
    reflection: "Cut my list in half after reading this, and it actually worked.",
  },
  {
    text: "Craft is just care that survived contact with a deadline.",
    author: "Greta Lindell",
    source: "studio notes",
    tags: ["craft", "work"],
    reflection: "The most accurate description of my job I've ever read.",
  },
  {
    text: "A question you're afraid to ask is a decision you've already made.",
    author: "Ines Wickham",
    source: "The Long Meridian",
    tags: ["decisions", "honesty"],
    reflection: "Uncomfortable to sit with. Correct, though.",
  },
  {
    text: "The work you avoid is usually the work that matters.",
    author: "Theo Braganza",
    source: "commencement address",
    tags: ["discipline", "focus"],
    reflection: "Written on a sticky note on my monitor now.",
  },
  {
    text: "Nostalgia is just grief that learned to smile.",
    author: "Maren Holt",
    source: "studio interview",
    tags: ["memory", "perspective"],
    reflection: "Read this the week after a big move and it made sense immediately.",
  },
]
