import type { RecipeCorpusEntry } from "./recipesCorpus.types"

/** Curated, hand-written recipes, each paired with a matching real photo. */
export const RECIPES_CORPUS: readonly RecipeCorpusEntry[] = [
  {
    title: "Weeknight Sourdough Focaccia",
    cuisine: "italian",
    difficulty: "medium",
    servings: 6,
    photoKey: "sourdough-focaccia",
    ingredients: [
      "1 ripe sourdough starter (100g)",
      "500g bread flour",
      "375ml warm water",
      "10g salt",
      "60ml olive oil, divided",
      "Cherry tomatoes and olives, halved",
      "Flaky salt and rosemary to finish",
    ],
    steps: [
      "Mix starter, flour, water, and salt into a shaggy dough; rest 30 minutes.",
      "Stretch and fold every 30 minutes for 2 hours.",
      "Oil a sheet pan generously, spread the dough, and let it relax for 10 minutes before dimpling.",
      "Cold-proof overnight in the fridge.",
      "Bring to room temp, press tomatoes and olives into the dimples, drizzle with the rest of the oil, and bake at 220°C for 25 minutes.",
    ],
    note: "First attempt came out dense because I rushed the cold proof — worth the overnight wait.",
  },
  {
    title: "Charred Corn and Black Bean Tacos",
    cuisine: "mexican",
    difficulty: "easy",
    servings: 4,
    photoKey: "street-tacos",
    ingredients: [
      "2 ears corn, husked",
      "1 can black beans, rinsed",
      "8 small corn tortillas",
      "1 avocado, sliced",
      "1 lime",
      "Cotija cheese",
      "Pickled red onion",
      "Cilantro",
    ],
    steps: [
      "Char the corn directly over a gas flame or grill until blackened in spots.",
      "Cut kernels off the cob and warm through with the black beans and a pinch of cumin.",
      "Warm tortillas, fill, and top with avocado, cotija, pickled onion, and cilantro.",
      "Finish with a squeeze of lime.",
    ],
  },
  {
    title: "Slow-Roasted Tomato Galette",
    cuisine: "french",
    difficulty: "medium",
    servings: 6,
    photoKey: "tomato-galette",
    ingredients: [
      "1 disc all-butter pie dough",
      "4 heirloom tomatoes, sliced and salted",
      "150g ricotta",
      "1 egg, beaten",
      "2 tbsp Dijon mustard",
      "Fresh thyme",
      "Parmesan",
    ],
    steps: [
      "Salt the tomato slices and let them drain on paper towels for 20 minutes.",
      "Roll out the dough, spread a thin layer of Dijon, then the ricotta.",
      "Arrange tomatoes over the ricotta, leaving a wide border.",
      "Fold the border over, brush with egg, and scatter thyme and parmesan.",
      "Bake at 200°C for 40 minutes until deeply golden.",
    ],
    note: "Salting and draining the tomatoes properly is the whole trick — skip it and the crust goes soggy.",
  },
  {
    title: "Miso Butter Salmon",
    cuisine: "japanese",
    difficulty: "easy",
    servings: 2,
    photoKey: "miso-salmon",
    ingredients: [
      "2 salmon fillets",
      "2 tbsp white miso",
      "1 tbsp butter, softened",
      "1 tbsp honey",
      "1 tsp rice vinegar",
      "Scallions, sliced",
      "Steamed rice",
    ],
    steps: [
      "Whisk miso, butter, honey, and vinegar into a paste.",
      "Coat the salmon and marinate 20 minutes.",
      "Broil skin-side down for 8-9 minutes until the top caramelizes.",
      "Scatter scallions and serve over rice.",
    ],
  },
  {
    title: "Lemon Ricotta Pancakes",
    cuisine: "american",
    difficulty: "easy",
    servings: 4,
    photoKey: "lemon-ricotta-pancakes",
    ingredients: [
      "1 cup ricotta",
      "3 eggs, separated",
      "1/2 cup flour",
      "Zest of 1 lemon",
      "2 tbsp sugar",
      "Butter for the pan",
      "Maple syrup",
    ],
    steps: [
      "Whisk ricotta, egg yolks, flour, zest, and sugar into a thick batter.",
      "Whip egg whites to soft peaks and fold in gently.",
      "Cook low and slow in butter, 3 minutes a side.",
      "Serve immediately with maple syrup — they deflate fast.",
    ],
  },
  {
    title: "Spiced Chickpea and Spinach Stew",
    cuisine: "indian",
    difficulty: "easy",
    servings: 4,
    photoKey: "chickpea-stew",
    ingredients: [
      "2 cans chickpeas, drained",
      "1 onion, diced",
      "3 cloves garlic",
      "1 tbsp garam masala",
      "1 tsp turmeric",
      "1 can crushed tomatoes",
      "4 cups spinach",
      "A splash of coconut milk",
    ],
    steps: [
      "Sauté the onion and garlic until soft.",
      "Bloom the spices in the oil for 30 seconds.",
      "Add tomatoes and chickpeas, simmer 20 minutes.",
      "Stir in spinach until wilted, then finish with a splash of coconut milk.",
    ],
  },
  {
    title: "Brown Butter Sage Gnocchi",
    cuisine: "italian",
    difficulty: "medium",
    servings: 4,
    photoKey: "brown-butter-gnocchi",
    ingredients: [
      "500g potato gnocchi",
      "4 tbsp butter",
      "10 fresh sage leaves",
      "Parmesan, grated",
      "Black pepper",
    ],
    steps: [
      "Boil the gnocchi until they float, then drain.",
      "Melt the butter over medium heat until it smells nutty and turns golden brown.",
      "Fry sage leaves in the butter until crisp, about 30 seconds.",
      "Toss the gnocchi through the brown butter, top with parmesan and black pepper.",
    ],
    note: "Watch the butter closely in the last minute — the line between brown and burnt is about ten seconds.",
  },
  {
    title: "Smoky Black Pepper Ramen",
    cuisine: "japanese",
    difficulty: "medium",
    servings: 2,
    photoKey: "black-pepper-ramen",
    ingredients: [
      "2 portions fresh ramen noodles",
      "4 cups chicken stock",
      "2 tbsp soy sauce",
      "1 tbsp black pepper, coarsely cracked",
      "2 soft-boiled eggs",
      "Nori sheets",
      "Scallions",
    ],
    steps: [
      "Simmer the stock with soy sauce and black pepper for 15 minutes.",
      "Cook the noodles separately and drain.",
      "Divide noodles into bowls and ladle over the broth.",
      "Top with halved eggs, nori, and scallions.",
    ],
  },
  {
    title: "Honey Garlic Roast Chicken Thighs",
    cuisine: "american",
    difficulty: "easy",
    servings: 4,
    photoKey: "honey-garlic-chicken",
    ingredients: [
      "8 bone-in chicken thighs",
      "4 cloves garlic, minced",
      "3 tbsp honey",
      "2 tbsp soy sauce",
      "1 tbsp rice vinegar",
      "Roasted potatoes",
    ],
    steps: [
      "Whisk garlic, honey, soy sauce, and vinegar.",
      "Toss the chicken in the marinade for at least 1 hour.",
      "Roast skin-side up at 200°C for 35-40 minutes, basting halfway.",
      "Rest 5 minutes before serving with roasted potatoes.",
    ],
  },
  {
    title: "Dutch Baby with Caramelized Apples",
    cuisine: "american",
    difficulty: "easy",
    servings: 4,
    photoKey: "dutch-baby",
    ingredients: [
      "3 eggs",
      "1/2 cup flour",
      "1/2 cup milk",
      "1 tsp vanilla",
      "2 tbsp butter",
      "2 apples, thinly sliced",
      "2 tbsp brown sugar",
      "Cinnamon",
      "Powdered sugar to finish",
    ],
    steps: [
      "Preheat a cast-iron skillet in a 220°C oven with the butter.",
      "Blend the eggs, flour, milk, and vanilla until smooth.",
      "Toss the apples with brown sugar and cinnamon, and scatter into the hot skillet.",
      "Pour the batter over the apples and bake 18-20 minutes until dramatically puffed.",
      "Dust with powdered sugar and serve immediately — it deflates within minutes.",
    ],
    note: "First batch collapsed before it reached the table because I stopped to take a photo. Worth planning the shot in advance.",
  },
]
